srcs/rails/files/config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  resources :guild_invites
  resources :room_users
  resources :blocklists
  resources :matches
  resources :wars
  resources :addons
  resources :friends
  resources :messages
  resources :rooms
  resources :guilds

  root 'users#edit'
  # root 'welcome#index'
  get 'welcome' => 'welcome#index'
# ------------------
#    GUILDS PAGE
# ------------------
  get 'guilds/index'
  get '/get_guild_users/:id', to: 'guilds#get_guild_users'
  put '/get_guild_users/:id', to: 'guilds#user_update'
  get '/get_owner_nick/:id', to: 'guilds#get_owner_nick'
  post 'guilds/join'
  post 'create_new_guild' => 'guilds#create_new_guild', as: 'create_new_guild'
  post 'guilds/exit'
  get 'guilds/exit' => 'guilds#exit'
  post 'guilds/add_officer'
  post 'guilds/delete_officer'
  post 'guilds/delete_member'
  get 'get_guilds' => "guilds#get_guilds", as: 'get_guilds'
  get 'get_curr_user' => "guilds#get_curr_user", as: 'get_curr_user'
  post 'guilds/update_name' => "guilds#update_name"
  post 'guilds/update_anagram' => "guilds#update_anagram"
  post 'guilds/update_logo' => "guilds#update_logo"
  get 'guilds/get_guild/:id' => 'guilds#get_guild'

  get 'guilds/is_officer/:id' => 'guilds#is_officer'
  get 'guilds/is_owner/:id' => 'guilds#is_owner'
  get 'guilds/exit_user/:id' => 'guilds#exit_user'
  get 'guilds/do_owner/:id' => 'guilds#do_owner'
  get 'guilds/do_officer/:id' => 'guilds#do_officer'
  get 'guilds/undo_officer/:id' => 'guilds#undo_officer'

  get '/guilds_list' => 'guilds#guilds_list'

# ------------------
#   GUILDS INVITES
# ------------------
  get 'guild_invites/invite_to_guild/:id' => 'guild_invites#invite_to_guild'
  get 'guild_invites/users_invites/:id' => 'guild_invites#users_invites'
  get 'guild_invites/accept_invitation/:id' => 'guild_invites#accept_invitation'
  get 'guild_invites/decline_invitation/:id' => 'guild_invites#decline_invitation'
  get 'guild_invites/del_all_invites/:id' => 'guild_invites#del_all_invites'

# ------------------
#    PROFILE PAGE
# ------------------
  get '/user' => "profile#index"
  get '/user/:id' => "users#show"
  get 'profile/get_curr_user' => "profile#get_curr_user"
  get 'profile/:id' => "profile#index"
  get 'profile/get_user/:id' => "profile#get_user"
  get 'profile/ban_user/:id' => "profile#ban_user"
  get 'profile/unban_user/:id' => "profile#unban_user"
  get 'profile/undo_moderator_user/:id' => "profile#undo_moderator_user"
  get 'profile/do_moderator_user/:id' => "profile#do_moderator_user"

  get 'block_list' => "profile#block_list"
  get 'profile/block_list_detailed/:id' => "profile#block_list_detailed"
  get 'blocklists/unblock_user/:id' => 'blocklists#unblock_user'
  get 'blocklists/unblock_user_by_id/:id' => 'blocklists#unblock_user_by_id'
  get 'blocklists/block_user/:id' => 'blocklists#block_user'
  get 'blocklists/is_blocked/:id' => 'blocklists#is_blocked'

  get 'users' => "users#edit"
  post 'users/update_avatar' => "users#update_avatar"
  post 'users/edit/update_avatar' => "users#update_avatar"
  post 'users/update_nickname' => "users#update_nickname"
  post 'users/edit/update_nickname' => "users#update_nickname"
  post 'users/block_user' => 'users#block_user'
  post 'rooms/block_user' => 'users#block_user'
  post 'users/unblock_user' => 'users#unblock_user'
  post 'rooms/unblock_user' => 'users#unblock_user'

  get 'users/online' => 'users#online'
  get '/leaderboard' => 'users#index'
  get '/users_list' => 'users#users_list'

# ------------------------------------
#   PROFILE PAGE - FRIENDS CONTROLLER
# ------------------------------------
  get 'friends/get_friends/:id' => 'friends#get_friends'
  get 'friends/get_followers/:id' => 'friends#get_followers'
  get 'friends/is_friend/:id' => 'friends#is_friend'
  get 'friends/follow_back/:id' => 'friends#follow_back'
  get 'friends/send_request/:id' => 'friends#send_request'
  get 'friends/delete_from_friends/:id' => 'friends#delete_from_friends'
  get 'friends/unfollow_user/:id' => 'friends#unfollow_user'

# ------------------
#    CHAT PAGE
# ------------------
  post 'rooms/pass_check' => 'rooms#pass_check'
  post 'rooms/create' => 'rooms#create'
  post 'rooms/leave' => 'rooms#leave'
  post 'rooms/change_pass' => 'rooms#change_pass'
  post 'change_pass' => 'rooms#change_pass'
  post 'rooms/do_admin' => 'rooms#do_admin'
  post 'rooms/rm_admin' => 'rooms#rm_admin'
  post 'rooms/mute_user' => 'rooms#mute_user'
  post 'rooms/new_match' => 'matches#new_match'
  post 'rooms/kick' => 'rooms#kick'

  post 'rooms/watch_stream' => 'matches#watch_stream'

# ------------------
#    GAME PAGE
# ------------------
  get 'matches/match_users/:id' => 'matches#match_users'
  put 'matches/match_users/:id' => 'matches#match_users_update'

  get 'matches/get_player/:id' => 'matches#get_player'
  post 'matches/new_match' => 'matches#new_match'

  get 'matches/users_matches/:id' => 'matches#users_matches'
  get 'create_random_match' => 'matches#create_random_match'
  get 'random_matches' => 'matches#random_matches'
  get 'new_match_profile/:id' => 'matches#new_match_profile'

  post 'matches/end_game' => 'matches#end_game'
  get 'matches/war_matches/:id' => 'matches#war_matches'

# ------------------
# WARS
# ------------------
  get 'wars/guild_wars/:id' => 'wars#guild_wars'
  get 'wars/decline/:id' => 'wars#decline'
  get 'wars/accept/:id' => 'wars#accept'

  post 'create_war_match' => 'wars#create_war_match'
  post '/wars/join_match' => 'wars#join_match'

# ------------------
# TOURNAMENTS
# ------------------
  get '/tournaments/result/:id' => 'tournaments#result'
  post '/tournaments/join' => 'tournaments#join'
  get '/tournaments/leave/:id' => 'tournaments#leave'
  get '/tournaments/members/:id' => 'tournaments#members'
  get '/tournaments/matches/:id' => 'tournaments#matches'
  get '/tournaments/curr_user_is_in_tournament/:id' => 'tournaments#curr_user_is_in_tournament'

# --------------------
#    AUTHENTIFICATION
# --------------------
  post 'users/enable_otp' => 'users#enable_otp'
  post 'users/disable_otp' => 'users#disable_otp'
  post 'users/edit/enable_otp' => 'users#enable_otp'
  post 'users/edit/disable_otp' => 'users#disable_otp'
  get 'users/edit/profile/0' => 'profile'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_path
    post '/users/auth/marvin/twofa' => 'users/omniauth_callbacks#twofa'
  end

  post '/notification/destroy' => 'notification#destroy'
  get '*unmatched_route', to: 'application#raise_not_found'
end

srcs/rails/files/app/views/welcome/index.html.erb
<div class='row'>
	<div class='col-1'></div>
	<div class='col-10 center_align lightText'>
		<h2 class='titletext'>
			Welcome to ft_transcendence site!
		</h2>
		<div style='margin-top: 20px'>
			The aim of this site is to play a <a class='rulesLink' href="https://en.wikipedia.org/wiki/Pong" target="_blank">pong game</a> from 1972.</p>	
		</div>
		<div class='row RulesRow'>
			<div class='col-4'>
				<div class='card RulesCard'>
					<a class='SimpleHref' href='/matches'>
						<div class="card-body">
        					<h5 class="titletext">GAME</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							You can play online pong game with your friends (friendly match) or with random users (rating match)
         				</li>
						<li class="list-group-item MatchesCreationList">
							Match lasts up to 7 points
         				</li>
						 <li class="list-group-item MatchesCreationList">
							If you leave game page before ending, your opponent will earn one point
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can choose different types of game addons and their combinations: none, boost, dicso, epilepsy
         				</li>
						<li class="list-group-item MatchesCreationList">
							If the match is rating the difference in points will be counted as a rating (score). 
							You can check your score on yours 
							<a class='rulesLink' href="/profile/0">profile page</a>
							or on
							<a class='rulesLink' href="/leaderboard">leaderboard</a>
         				</li>
					</div>
				</div>
			</div>
			<div class='col-4'>
				<div class='card RulesCard'>
					<a class='SimpleHref' href='/tournaments'>
					 	<div class="card-body">
        					<h5 class="titletext">TOURNAMENT</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							Site admins and moderators are able to create tournaments
         				</li>
						<li class="list-group-item MatchesCreationList">
							Before the start of the tournament, everyone can join it
         				</li>
						<li class="list-group-item MatchesCreationList">
							Tournaments are scheduled for a specific time
         				</li>
						<li class="list-group-item MatchesCreationList">
							When the tournament starts, matches are created between all participants. 
							Chat with all your opponents and agree on the time of the match.
         				</li>
						<li class="list-group-item MatchesCreationList">
							When the tournament time ends, all matches end automatically
						</li>
						<li class="list-group-item MatchesCreationList">
							Prize points will be awarded to the winner of the tournament
						</li>
					</div>
				</div>
			</div>
			<div class='col-4'>
				<div class='card RulesCard'>
					<a class='SimpleHref' href='/wars'>
						<div class="card-body">
        					<h5 class="titletext">WAR</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							Any <a class='rulesLink' href="/guilds">guild</a> owner or guild officer can declare a war to another guild. Opponent guild can accept or decline the war.
         				</li>
						<li class="list-group-item MatchesCreationList">
							War date and time - date and time of the beginning and end of the war. The guild can accept the war only if no other war is sheluded at the same time.
         				</li>
						<li class="list-group-item MatchesCreationList">
							War addons - all the matches of the war will be with these addons
         				</li>
						<li class="list-group-item MatchesCreationList">
							War prize - the number of points that will be subtracted from the loser guild and awarded to the winner guild
         				</li>
					</div>
				</div>
			</div>
		</div>

		<div class='row RulesRow' style='margin-top: 25px;'>
			<div class='col-4'>
				<div class='card RulesCard RulesCard'>
					<a class='SimpleHref' href='/profile/0'>
						<div class="card-body">
        					<h5 class="titletext">PROFILE</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							On profile page you can find all information about your user. Statistics, guild information, matches, friends
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can <a class='rulesLink' href="/users/edit/">edit</a> your profile avatar and nickname
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can <a class='rulesLink' href="/users/edit/">enable/disable</a> two factor authentication. You can use 
							<a class='rulesLink' href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=ru&gl=US" target="_blank">this application</a>
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can add other users to friends, delete from friends, accept or decline friend requests. You can block another user so that you won't see messages from him/her in <a class='rulesLink' href="/rooms">chat</a>
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can invite other users in <a class='rulesLink' href="/matches">matches</a> or <a class='rulesLink' href="/guilds">guilds</a> from profile page
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can create private chats with other users from their profile page
         				</li>
					</div>
				</div>
			</div>
			<div class='col-4'>
				<div class='card RulesCard'>
					<a class='SimpleHref' href='/guilds'>
						<div class="card-body">
        					<h5 class="titletext">GUILDS</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							You can create your own guild or join existing guild via invitation
         				</li>
						<li class="list-group-item MatchesCreationList">
							Guild owners can select guild logo and change name or anagram
         				</li>
						<li class="list-group-item MatchesCreationList">
							Guild owners can appoint a member as an officer
         				</li>
						<li class="list-group-item MatchesCreationList">
							Guild owners and officers are able to declare <a class='rulesLink' href="/wars">wars</a> to another guilds and to accept/decline war invitations
         				</li>
						<li class="list-group-item MatchesCreationList">
							All guild members can invite other users in their guilds (on user <a class='rulesLink' href="/profile/0">profile page</a>)
         				</li>
						<li class="list-group-item MatchesCreationList">
							Points earned by a guild member in any match are added to the guild score
						</li>
					</div>
				</div>
			</div>
			<div class='col-4'>
				<div class='card RulesCard'>
					<a class='SimpleHref' href='/rooms'>
						<div class="card-body">
        					<h5 class="titletext">CHAT</h5>
      					</div>
					</a>
					<div class="list-group list-group-flush RulesCardLi" id="list-tab" role="tablist">
						<li class="list-group-item MatchesCreationList">
							You can create, join or leave chat rooms to communicate with other users. Chat room can be public or you can set a password for the room
         				</li>
						<li class="list-group-item MatchesCreationList">
							You can create private chats with other users. Press 'send message' button on usres <a class='rulesLink' href="/profile/0">profile page</a> or tap on users message and choose 'direct' option
         				</li>
						<li class="list-group-item MatchesCreationList">
							By clicking on a message from a user, you can write him a private message, challenge him/her to a duel, block user
         				</li>
						<li class="list-group-item MatchesCreationList">
							If you are a room creator you can appoint a participant as a moderator
         				</li>
						<li class="list-group-item MatchesCreationList">
							If you are a room creator or a moderator can ban, kick or mute member for 1 minute
         				</li>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div class='col-1'></div>
</div>





<% if user_signed_in? && current_user.is_banned? %>
	<h3>You account was blocked by administrator</h3>
<% elsif !user_signed_in? %>
	<h2>Hi!</h2>
<% end %>
<% if !user_signed_in? %>
	<%= link_to "Log in", new_session_path(User.new) %>
	<%= link_to "Sign up", new_registration_path(User.new) %>
<% end %>